pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  buildId: "1$(Build.BuildId)"

steps:
# Print buildId
- script: |
    echo "BuildId = $(buildId)"
# Install SonarScanner
- script: |
    dotnet tool install --global dotnet-sonarscanner
# Begin SonarScanner#
- script: |
    %USERPROFILE%\.dotnet\tools\dotnet-sonarscanner begin /k:"c1gdoyle_Dunk.Tools.Configuration" /d:sonar.organization="c1gdoyle" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$(SONAR_TOKEN)" /v:"$(buildId)" /d:sonar.cs.vstest.reportsPaths="**\TestResults\*.trx" /d:sonar.cs.opencover.reportsPaths="**\coverage.opencover.xml"
# Build source, tests and run tests for net472 (with coverage)
- script: |
    dotnet test ./Dunk.Tools.Configuration.Test/Dunk.Tools.Configuration.Test.csproj --configuration $(buildConfiguration) --framework net472 --logger:trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
# End SonarScanner
- script: |
    %USERPROFILE%\.dotnet\tools\dotnet-sonarscanner end /d:sonar.login="$(SONAR_TOKEN)"
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'