using System;
using System.Collections.Specialized;
using System.Configuration;
using System.Web.Configuration;
using Dunk.Tools.Configuration.Base;

namespace Dunk.Tools.Configuration.Core
{
    /// <summary>
    /// An implementation of <see cref="IConfigurationManager"/> that serves as a wrapper
    /// over this application's default <see cref="WebConfigurationManager"/>.
    /// </summary>
    public sealed class WebConfigurationManagerAdapter : IConfigurationManager
    {
        /// <summary>
        /// Gets the <see cref="System.Configuration.AppSettingsSection"/> data for the current application's
        /// default configuration.
        /// </summary>
        /// <returns>
        /// Returns a <see cref="NameValueCollection"/> object that contains the contents of the 
        /// <see cref="AppSettingsSection"/> object for the current application's default
        /// configuration.
        /// </returns>

        public NameValueCollection AppSettings
        {
            get { return WebConfigurationManager.AppSettings; }
        }

        /// <summary>
        /// Gets the <see cref="System.Configuration.ConnectionStringsSection"/> data for the current application's
        /// default configuration.
        /// </summary>
        /// <returns>
        /// Returns a <see cref="ConnectionStringSettingsCollection"/> object that contains the contents of the 
        /// <see cref="ConnectionStringsSection"/> object for the current application's default
        /// configuration.
        /// </returns>
        public ConnectionStringSettingsCollection ConnectionStrings
        {
            get { return WebConfigurationManager.ConnectionStrings; }
        }

        /// <summary>
        /// Retrieves a specified configuration section for the current application's default
        /// configuration.
        /// </summary>
        /// <typeparam name="T">The type associated with the configuration section.</typeparam>
        /// <param name="sectionName">The configuration section path and name.</param>
        /// <returns>
        /// The specified <see cref="ConfigurationSection"/> object, or null if the
        /// section does not exist.
        /// </returns>
        public T GetSection<T>(string sectionName)
        {
            return (T)WebConfigurationManager.GetSection(sectionName);
        }

        /// <summary>
        /// Gets a specific AppSetting as a specified type.
        /// </summary>
        /// <typeparam name="T">The type that is begin requested.</typeparam>
        /// <param name="key">Key of AppSetting to retrieve.</param>
        /// <returns>
        /// If able to return as the type then the converted value; otherwise an exception will be thrown.
        /// </returns>
        public T GetAppSettingsAsType<T>(string key)
        {
            return Utilities.GetAppSettingsHelper.AsType<T>(AppSettings, key);
        }

        /// <summary>
        /// Gets a specified AppSetting as a specified type or default value for that type.
        /// </summary>
        /// <typeparam name="T">The type that is begin requested.</typeparam>
        /// <param name="key">Key of AppSetting to retrieve.</param>
        /// <returns>
        /// If able to return as the type then the converted value; otherwise the default value for the type.
        /// </returns>
        public T GetAppSettingsAsTypeOrDefault<T>(string key)
        {
            return Utilities.GetAppSettingsHelper.AsTypeOrDefault<T>(AppSettings, key);
        }

        /// <summary>
        /// Gets a specific AppSetting as a specified type or specified default value for that type.
        /// </summary>
        /// <typeparam name="T">The type that is begin requested.</typeparam>
        /// <param name="key">Key of AppSetting to retrieve.</param>
        /// <param name="defaultValue">The default instance of T.</param>
        /// <returns>
        /// If able to return as the type then the converted value; otherwise <paramref name="defaultValue"/>.
        /// </returns>
        public T GetAppSettingsAsTypeOrDefault<T>(string key, T defaultValue)
        {
            return Utilities.GetAppSettingsHelper.AsTypeOrDefault(AppSettings, key, defaultValue);
        }

        /// <summary>
        /// Gets a specific AppSetting as a specified type or specified default value for that type.
        /// </summary>
        /// <typeparam name="T">The type that is begin requested.</typeparam>
        /// <param name="key">Key of AppSetting to retrieve.</param>
        /// <param name="defaultFactory">A delegate for generating a default instance of T.</param>
        /// <returns>
        /// If able to return as the type then the converted value; otherwise default value generated by
        /// <paramref name="defaultFactory"/>.
        /// </returns>
        public T GetAppSettingsAsTypeOrDefault<T>(string key, Func<T> defaultFactory)
        {
            return Utilities.GetAppSettingsHelper.AsTypeOrDefault(AppSettings, key, defaultFactory());
        }
    }
}
